### ISSUE TITLE
[FEATURE] Tangent vertex attribute

### ISSUE THREAD

**Issue by nicopap** [FractalFir/tmf#10]
I'd like to be able to store tangents in my tmf files.

Storing tangents in a serialized mesh format is a way to avoid expensive computation at runtime. Hence reducing load time. In fact  `glTF` specifies tangents as a standard field for their model file format. Quoting <https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#meshes-overview>

> XYZW vertex tangents where the XYZ portion is normalized, and the W component is a sign value (-1 or +1) indicating handedness of the tangent basis

Those look very much like a normal (with the one additional +1 -1 component).

**Comment by FractalFir** [comment]
Which API representations for tangents would be easier to work with? One where w is represented as a bool denoting handedness or as a float with value of either -1 or 1? The representation on disk will be the same, and any performance difference negligible. I don't know the use cases for tangents look like exactly, so it is hard for me to envision which would be more ergonomic to use.

**Comment by FractalFir** [comment]
170bf3197fd2f0b23074649e7afbab98637d637f adds support for setting/getting tangent arrays on a mesh and saving them to disk (reading is partially implemented). Current API representation of Tangent is tuple ((float, float, float), float). I am still looking for feedback on this API representation of tangents.

**Comment by FractalFir** [comment]
fee157aa296ad845e02ec3a6b4a4731c339828d4 adds support for reading tangents from disk. After tangent triangle segment will be added, this feature will be complete.

**Comment by FractalFir** [comment]
ac53b94a689316993130687694abff1f93e336af adds support for saving and loading tangent triangle index arrays. This feature is complete, and I am just waiting for more input on the current API.

**Comment by nicopap** [comment]
I noticed there is no way to read the value of `HandenesType` (also, I think it should be spelled `Handedness`). Maybe add a `get()` method or make the field `pub`?

**Comment by nicopap** [comment]
I've done the following on the fork I use

```rust
impl From<FloatType> for HandenesType {
    fn from(value: FloatType) -> Self {
        HandenesType(value)
    }
}
impl From<HandenesType> for FloatType {
    fn from(value: HandenesType) -> Self {
        value.0
    }
}
```

**Comment by FractalFir** [comment]
`HanenessType` being a struct was an oversight on my part (something temporary that I forgot to remove).  `HanenessType`  was supposed to be entirely internal (just a normal float to the consumer of the API), as a way to make functions signatures more clear. Now it is just an alias for `FloatType`, which is an alias for either `f32` or `f64`, depending on feature flags set.

**Comment by FractalFir** [comment]
Since there are no more comments, I assume the current API is OK.
